### ISSUE TITLE
How to deploy without exposing Authentication Key?

### ISSUE THREAD

**Issue by jackbisceglia** [kescardoso/pictury#22]
We have a potential issue, where calling the Unsplash API directly would require our API key to be deployed with the extension itself. 

My Potential Workarounds:
 - Reach out to Unsplash directly and see if we could get a more generic public key for the app itself?
 - Wrap our API calls into our own REST API
   - In this scenario, we could deploy a REST API that our extension calls
   - Our REST API would then make the calls to Unsplash's API, so that we could hide our key from the public

**Comment by kescardoso** [comment]
Hi @jackbisceglia let me know if this issue can be closed.
Thanks!

**Comment by kescardoso** [comment]
Fix left for future versions (from v.0.01 to v.0.02)
