### ISSUE TITLE
Create the UI portion of the Extension

### ISSUE THREAD

**Issue by jackbisceglia** [kescardoso/pictury#4]
I think the best way to go about the extension is having a UI that is accessible from the far left sidebar on VSCode, for example:
   - <img src="https://i.imgur.com/jNIyIif.png" />

Before integrating Svelte, we should definitely research how to get the UI portion to work on a fundamental level, and then we can implement our framework and build out the UI

**Comment by kescardoso** [comment]
Currently integrating design rules with bootstrap css and js (margin, paddding, header, footer).
Next steps:
- Add more info to the instructiuons accordion
- Style the search form
- Add image overlay (with image actions as text) on each image on grid results
