### ISSUE TITLE
Add credits to the pictures' authors

### ISSUE THREAD

**Issue by Ali-Doggaz** [kescardoso/pictury#59]
When displaying a photo from Unsplash, your application must attribute Unsplash, the Unsplash photographer, and contain a link back to their Unsplash profile. All links back to Unsplash should use utm parameters in the ?utm_source=your_app_name&utm_medium=referral . More info & examples → https://help.unsplash.com/en/articles/2511315-guideline-attribution

**Comment by Ali-Doggaz** [comment]
+ Add credits to unsplash for all the pictures

**Comment by dev2919** [comment]
Hey @Ali-Doggaz, 👋 can I work on this issue if you haven't started on it yet.

**Comment by ravisha7feb** [comment]
> Hey @Ali-Doggaz, 👋 can I work on this issue if you haven't started on it yet.

Yup! @dev2919 and I would like to work on this :)

**Comment by Ali-Doggaz** [comment]
It would be with great pleasure   @ravisha7feb @dev2919 ! You can add me on discord "Ali Doggaz#8099" and I'll add you to the team chat.
