### ISSUE TITLE
A clearly visible notification of "Picture URL copied"

### ISSUE THREAD

**Issue by ravisha7feb** [kescardoso/pictury#66]
**Issue:**
Right now, when we left-click on a photograph, the URL gets copied and we get a notification on the debug bar which is often too small to notice for the user. They might not know that they have just copied the URL. 
**Solution:**
This can be fixed by giving a relatively larger notification right on that photograph.

**Comment by ravisha7feb** [comment]
> **Issue:**
> Right now, when we left-click on a photograph, the URL gets copied and we get a notification on the debug bar which is often too small to notice for the user. They might not know that they have just copied the URL.
> **Solution:**
> This can be fixed by giving a relatively larger notification right on that photograph.

@dev2919 and I would like to work on this.

**Comment by Ali-Doggaz** [comment]
Good Idea!

**Comment by dev2919** [comment]
> > **Issue:**
> > Right now, when we left-click on a photograph, the URL gets copied and we get a notification on the debug bar which is often too small to notice for the user. They might not know that they have just copied the URL.
> > **Solution:**
> > This can be fixed by giving a relatively larger notification right on that photograph.
> 
> @dev2919 and I would like to work on this.

Yes will be joining @ravisha7feb with this issue

**Comment by Ali-Doggaz** [comment]
Issue solved: We now have a clear notification for both downloads and URL copies.
